-- =============================================================================
-- Cruise Yield Optimization - RAW Layer Tables
-- Layer: Bronze (Raw Ingested Data)
-- Description: Source tables for all raw data ingestion
-- =============================================================================

USE SCHEMA CRUISE_YIELD_OPTIMIZATION.RAW;

CREATE OR REPLACE STAGE DATA_STAGE
    COMMENT = 'Stage for loading synthetic data files'
    DIRECTORY = (ENABLE = TRUE);

CREATE OR REPLACE TABLE SAILINGS (
    SAILING_ID VARCHAR(10),
    SHIP_NAME VARCHAR(100) NOT NULL,
    SHIP_CLASS VARCHAR(50),
    CAPACITY NUMBER(38,0),
    ITINERARY_REGION VARCHAR(50),
    DEPARTURE_PORT VARCHAR(100),
    DURATION_NIGHTS NUMBER(38,0),
    SAILING_DATE DATE,
    SEASON_MULTIPLIER NUMBER(4,2),
    BASE_OCCUPANCY_TARGET NUMBER(4,2),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE GUESTS (
    GUEST_ID VARCHAR(20),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(200),
    LOYALTY_TIER VARCHAR(20),
    LOYALTY_POINTS NUMBER(38,0),
    PAST_CRUISES NUMBER(38,0),
    LIFETIME_VALUE NUMBER(12,2),
    AVG_ONBOARD_SPEND NUMBER(10,2),
    PRICE_SENSITIVITY NUMBER(4,2),
    PREFERRED_CABIN_CLASS VARCHAR(30),
    PREFERRED_REGION VARCHAR(50),
    GUEST_SEGMENT VARCHAR(50),
    MEMBER_SINCE DATE,
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BOOKINGS (
    BOOKING_ID VARCHAR(20),
    GUEST_ID VARCHAR(20) NOT NULL,
    SAILING_ID VARCHAR(10) NOT NULL,
    BOOKING_DATE DATE,
    SAILING_DATE DATE,
    CABIN_CLASS VARCHAR(30),
    NUM_GUESTS NUMBER(38,0),
    BASE_PRICE NUMBER(10,2),
    OFFERED_PRICE NUMBER(10,2),
    TOTAL_CABIN_REVENUE NUMBER(12,2),
    BOOKING_STATUS VARCHAR(20),
    DAYS_BEFORE_SAILING NUMBER(38,0),
    BOOKING_CHANNEL VARCHAR(50),
    PROMO_CODE_USED BOOLEAN,
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ONBOARD_SPENDING (
    TRANSACTION_ID VARCHAR(20),
    BOOKING_ID VARCHAR(20) NOT NULL,
    GUEST_ID VARCHAR(20) NOT NULL,
    SAILING_ID VARCHAR(10) NOT NULL,
    TRANSACTION_DATE DATE,
    CATEGORY VARCHAR(50),
    AMOUNT NUMBER(10,2),
    VENUE VARCHAR(100),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PRECRUISE_PURCHASES (
    PURCHASE_ID VARCHAR(20),
    BOOKING_ID VARCHAR(20) NOT NULL,
    GUEST_ID VARCHAR(20) NOT NULL,
    SAILING_ID VARCHAR(10) NOT NULL,
    PURCHASE_DATE DATE,
    PACKAGE_NAME VARCHAR(100),
    PACKAGE_CATEGORY VARCHAR(50),
    PRICE NUMBER(10,2),
    QUANTITY NUMBER(38,0),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PRICING_EVENTS (
    EVENT_ID VARCHAR(20),
    GUEST_ID VARCHAR(20) NOT NULL,
    SAILING_ID VARCHAR(10) NOT NULL,
    CABIN_CLASS VARCHAR(30),
    EVENT_DATE DATE,
    OFFERED_PRICE NUMBER(10,2),
    CONVERTED BOOLEAN,
    SESSION_ID VARCHAR(50),
    DEVICE_TYPE VARCHAR(20),
    TIME_ON_PAGE_SECONDS NUMBER(38,0),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PARTNER_SIGNALS (
    SIGNAL_ID VARCHAR(20),
    SIGNAL_DATE DATE,
    DEPARTURE_PORT VARCHAR(100),
    AIRPORT_CODE VARCHAR(10),
    SIGNAL_TYPE VARCHAR(50),
    PRICE_INDEX NUMBER(6,1),
    DEMAND_SCORE NUMBER(4,2),
    CAPACITY_UTILIZATION NUMBER(4,2),
    AVG_FARE NUMBER(10,2),
    IS_ANOMALY BOOLEAN,
    ANOMALY_DESCRIPTION VARCHAR(500),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE GUEST_FEEDBACK (
    FEEDBACK_ID VARCHAR(20) NOT NULL,
    GUEST_ID VARCHAR(20) NOT NULL,
    BOOKING_ID VARCHAR(20) NOT NULL,
    SAILING_ID VARCHAR(10) NOT NULL,
    SHIP_NAME VARCHAR(100),
    FEEDBACK_DATE DATE,
    OVERALL_RATING NUMBER(38,0),
    CATEGORY VARCHAR(50),
    SUBCATEGORY VARCHAR(100),
    RATING NUMBER(38,0),
    SENTIMENT VARCHAR(20),
    FEEDBACK_TEXT VARCHAR(2000),
    MENTIONED_AMENITIES VARCHAR(500),
    MENTIONED_EXCURSIONS VARCHAR(500),
    WOULD_RECOMMEND BOOLEAN,
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (FEEDBACK_ID)
);
