-- =============================================================================
-- Cruise Yield Optimization - CURATED Layer Tables
-- Layer: Silver (Cleansed and Enriched Data)
-- Description: Tables for enriched guest data
-- =============================================================================

USE SCHEMA CRUISE_YIELD_OPTIMIZATION.CURATED;

CREATE OR REPLACE TABLE GUEST_FLIGHTS (
    FLIGHT_ID VARCHAR(30),
    GUEST_360_ID VARCHAR(20),
    BOOKING_ID VARCHAR(20),
    AIRLINE VARCHAR(50),
    FLIGHT_NUMBER VARCHAR(20),
    ORIGIN_AIRPORT VARCHAR(10),
    ORIGIN_CITY VARCHAR(100),
    DESTINATION_AIRPORT VARCHAR(10),
    DESTINATION_CITY VARCHAR(100),
    FLIGHT_DATE DATE,
    FLIGHT_TYPE VARCHAR(20),
    TICKET_PRICE NUMBER(10,2),
    BOOKING_SOURCE VARCHAR(30)
);

CREATE OR REPLACE TABLE GUEST_SERVICES (
    SERVICE_ID VARCHAR(30),
    GUEST_360_ID VARCHAR(20),
    SERVICE_DATE DATE,
    SERVICE_CATEGORY VARCHAR(50),
    SERVICE_NAME VARCHAR(100),
    AMOUNT NUMBER(10,2),
    SAILING_ID VARCHAR(20),
    PURCHASE_CHANNEL VARCHAR(30)
);
